name: Generate Profile Image


on:
    push:
        branches: [main]
    workflow_dispatch:


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Freeze
              run: |
                wget -qO freeze.deb https://github.com/charmbracelet/freeze/releases/download/v0.1.6/freeze_0.1.6_amd64.deb
                sudo dpkg -i freeze.deb
                rm freeze.deb

            - name: Generate Profile Image
              run: freeze profile.py -o ./assets/profile.png --language python -m 20 --window -r 8 --border.width 1 --theme rose-pine --font.ligatures

            - name: Commit and push changes
              run: |
                git config --global user.name 'github-actions[bot]'
                git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
                git add assets/profile.png
                git commit -m "ci: update profile image"
                git push
